// See https://aka.ms/new-console-template for more information
#pragma warning disable CS8618
public class Tclist
{
    public string teachCampus { get; set; }
    public string SFXZXB { get; set; }
    public string isRetakeClass { get; set; }
    public string department { get; set; }
    public string TJBJ { get; set; }
    public int NSKRL { get; set; }
    public int NVSKRL { get; set; }
    public int NSXKRS { get; set; }
    public int NVSXKRS { get; set; }
    public SKSJ[] SKSJ { get; set; }
    public string schoolTerm { get; set; }
    public string JXBID { get; set; }
    public string campus { get; set; }
    public string XQ { get; set; }
    public string KCH { get; set; }
    public string KCM { get; set; }
    public string KXH { get; set; }
    public string SKJS { get; set; }
    public string SKJSLB { get; set; }
    public string KKDW { get; set; }
    public string teachingPlace { get; set; }
    public string teachingPlaceHide { get; set; }
    public string XS { get; set; }
    public string XF { get; set; }
    public string examType { get; set; }
    public string hasTest { get; set; }
    public string isTest { get; set; }
    public string hasBook { get; set; }
    public int numberOfSelected { get; set; }
    public int numberOfFirstVolunteer { get; set; }
    public int classCapacity { get; set; }
    public string KCXZ { get; set; }
    public string KCLB { get; set; }
    public string courseType { get; set; }
    public string courseNature { get; set; }
    public string schoolClassMapStr { get; set; }
    public string SKJSZC { get; set; }
    public int KRL { get; set; }
    public int YXRS { get; set; }
    public int DYZYRS { get; set; }
    public string SFYX { get; set; }
    public string SFYM { get; set; }
    public string secretVal { get; set; }
    public string SFCT { get; set; }
    public string SFXZXK { get; set; }
    public string XGXKLB { get; set; }
    public string DGJC { get; set; }
    public string SFKT { get; set; }
    public string conflictDesc { get; set; }
    public string testTeachingClassID { get; set; }
    public string YPSJDD { get; set; }
    public string ZYDJ { get; set; }
    public string KSLX { get; set; }
    public string XDFS { get; set; }
    public string SFSC { get; set; }
}
